name: ci/cd

on:
  push:
    branches: ['*']


jobs:
  tinygo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
    - uses: acifani/setup-tinygo@v1
      with:
        tinygo-version: 0.26.0
    - run: tinygo build -o wasm.wasm -target wasm ./main.go
